### ISSUE TITLE
[FE] 카드 hover 효과 -  배송 정보 버그 수정

### ISSUE THREAD

**Issue by jaypedia** [hemudi/sidedish#32]
![mouse bug small](https://user-images.githubusercontent.com/34249911/165201107-2780cd7a-4c03-4f86-9ca4-859f80cfa5ca.gif)

**Comment by hemudi** [comment]
밀리 빨리 고쳐주세요 **٩(๑˃̌ۿ˂̌๑)۶**

**Comment by hemudi** [comment]
앟 고쳐주셨네여 굳굳 ^-^)b
