### ISSUE TITLE
[BE] 데이터베이스 설계 및 ERD 작성

### ISSUE THREAD

**Issue by devjun10** [hemudi/sidedish#8]
Description
----
데이터베이스 설계와 및 ERD에 관련된 이슈

<br/><br/>

- [x] 데이터베이스 설계 및 ERD 작성 
- [x] 데이터베이스 생성

**Comment by devjun10** [comment]
## ERD 
![리동다이어그램](https://user-images.githubusercontent.com/92818747/163958859-7b116730-b7fa-40b1-b3ab-24215c0811eb.png)

**Comment by donggi-lee-bit** [comment]
## ERD

![리동다이어그램](https://user-images.githubusercontent.com/73376468/164035785-8c2eac52-e412-4ca5-8848-3390bea74a75.png)
